### ISSUE TITLE
License

### ISSUE THREAD

**Issue by esloch** [eaglebh/blast-dbf#5]
Hi everyone!

I would like to know what's the license of this project? I'm planing to create a conda-package for this project and I need this information.

Thanks.

**Comment by eaglebh** [comment]
Hi @esloch , you can check the license info on the original project from where I based the code.
https://github.com/madler/zlib/tree/master/contrib/blast
I'm not changing anything about that, and the blast.h file has the original license without any modification.
The copyright is not mine, about my changes, you can use it following the original license.

**Comment by esloch** [comment]
Hi @eaglebh! Thanks for your quick response.
