### ISSUE TITLE
Can i run blast-dbf in windows?

### ISSUE THREAD

**Issue by Bortolazzi** [eaglebh/blast-dbf#8]
Hi, 
Is there any way to run blast-dbf directly from a Windows machine?
tks

**Comment by eaglebh** [comment]
Hi, I have not tried it on Windows.
But one option for you is to install Ubuntu using WSL for example, from microsoft store.
And use linux over windows, with access to your files.

**Comment by Bortolazzi** [comment]
Thanks! I'll try!
